### PR TITLE
Prime number calculation sped up + cleanup

### PR DESCRIPTION
**Pull request by sjvrijn**
The calculations in `is_prime(n)` only have to run up to `sqrt(n)`, and can skip any number of the form _2n_ and _3n_, leaving those of the form _6n+1_ and _6n+5_.
Cleanup:
- removed redundant parenthesis
- used augmented assignment where possible (+=, *=)
- replaced `while (1)` with `while True`
- indented comments to match code indentation

### CODE REVIEW

**Comment by sjvrijn** [comment]
Thanks for the comments, I'll fix them and create a new pull request

**Comment by naught101** [comment]
I think that if you update though branch the pull request should update automatically, no need to open a new one.

On 29 February 2016 10:17:32 pm AEDT, Sander notifications@github.com wrote:

> Thanks for the comments, I'll fix them and create a new pull request
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/naught101/sobol_seq/pull/4#issuecomment-190161193

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sjvrijn** [comment]
Fixes are up and thanks for the tip, didn't realize that

**Comment by naught101** [comment]
Great, thank you :)

**Pull request merged**
